### ISSUE TITLE
Create an image build Dockerfile that includes the VDDK

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-pods#635] opened 2020-10-01 21:48 UTC
While we can't actually build with the VDDK, we _can_ create a Dockerfile given someone has the VDDK and we can fetch it.  Not sure if an ARG with a URL is the best way or a COPY command, but having a Dockerfile would make the steps to rebuild the image including the VDDK much simpler.

@miq-bot add-label enhancement

**Comment by bdunne** [comment] 2020-12-24 00:18
Closing as duplicate of https://github.com/ManageIQ/manageiq-pods/issues/538

**Closed by bdunne** 2020-12-24 00:18 UTC
Labels: enhancement, help wanted
