### ISSUE TITLE
orchestrator pod keeps crashing

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#487] opened 2020-05-06 13:57 UTC
@miq-bot add_label bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I found that when re-install the manageiq operator, the orchestrator pod keeps crashing.

```console
[root@gyliu-ocp-1-inf ~]# oc logs -f orchestrator-5889bc5644-9dxfp
== Checking 172.30.17.20:11211 status ==
172.30.17.20:11211 - accepting connections
== Checking postgresql:5432 status ==
postgresql:5432 - accepting connections
== Writing encryption key ==
== Checking deployment status ==
{"@timestamp":"2020-05-05T14:47:18.793716 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"debug","message":"PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 1, in use: 1, waiting_in_queue: 0"}
{"@timestamp":"2020-05-05T14:47:19.026182 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"MIQ(Vmdb::Loggers.apply_config) Log level for azure.log has been changed to [WARN]"}
{"@timestamp":"2020-05-05T14:47:19.026797 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"MIQ(Vmdb::Loggers.apply_config) Log level for vim.log has been changed to [WARN]"}
{"@timestamp":"2020-05-05T14:47:19.166790 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"MIQ(SessionStore) Using session_store: ActionDispatch::Session::MemCacheStore"}
{"@timestamp":"2020-05-05T14:47:19.443788 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"debug","message":"Dalli::Server#connect 172.30.17.20:11211"}
{"@timestamp":"2020-05-05T14:47:19.753726 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"Initializing Environment for API"}
{"@timestamp":"2020-05-05T14:47:19.754069 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":""}
{"@timestamp":"2020-05-05T14:47:19.754222 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"Static Configuration"}
{"@timestamp":"2020-05-05T14:47:19.754387 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"  module                  : api"}
{"@timestamp":"2020-05-05T14:47:19.754502 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"  name                    : API"}
{"@timestamp":"2020-05-05T14:47:19.754608 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"  description             : REST API"}
{"@timestamp":"2020-05-05T14:47:19.754709 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":""}
{"@timestamp":"2020-05-05T14:47:19.754865 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"Dynamic Configuration"}
{"@timestamp":"2020-05-05T14:47:19.758888 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"  token_ttl               : 10.minutes"}
{"@timestamp":"2020-05-05T14:47:19.759113 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"  authentication_timeout  : 30.seconds"}
{"@timestamp":"2020-05-05T14:47:19.759307 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"  max_results_per_page    : 1000"}
{"@timestamp":"2020-05-05T14:47:19.759507 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"info","message":"MIQ(Vmdb::Initializer.init) - Program Name: bin/rake, PID: 15, ENV['EVMSERVER']: "}
{"@timestamp":"2020-05-05T14:47:19.759944 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"debug","message":"PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 1, in use: 0, waiting_in_queue: 0"}
{"@timestamp":"2020-05-05T14:47:22.349031 ","hostname":"orchestrator-5889bc5644-9dxfp","pid":15,"tid":"2aef2170395c","level":"debug","message":"PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 1, in use: 1, waiting_in_queue: 0"}
Deployment status is new_replica
New replica is not supported, exiting..
```

Bumping the `orchestratorInitialDelay: "2400"` fixed this issue.

FYI @carbonin

**Comment by carbonin** [comment] 2020-05-06 14:00
Duplicate of https://github.com/ManageIQ/manageiq-pods/issues/430

**Closed by carbonin** 2020-05-06 14:00 UTC
Labels: bug
