### ISSUE TITLE
orchestrator failed with "New replica is not supported, exiting.."

### ISSUE THREAD

**Issue by gabrielqi** [ManageIQ/manageiq-pods#576] opened 2020-07-06 07:04 UTC
I am trying to deploy it on OCP4.3 and the orchestrator is not starting, 

NAME                           READY     STATUS             RESTARTS   AGE
httpd-575b54f66b-ncrbf         1/1       Running            0          83m
kafka-5b57f47bf6-vr6st         1/1       Running            1          83m
memcached-65c956867-zttcd      1/1       Running            0          83m
orchestrator-fb675b57b-v9tc7   0/1       CrashLoopBackOff   18         83m
postgresql-5c48d48f8-hm958     1/1       Running            0          83m
zookeeper-55c6cbb8bc-klwct     1/1       Running            0          83m

and no more pods are created

After run ./bin/deploy parameters, I got crashed "orchestrator" with the following log info:
== Checking 172.30.102.24:11211 status ==
172.30.102.24:11211 - accepting connections
== Checking postgresql:5432 status ==
postgresql:5432 - accepting connections
== Writing encryption key ==
== Checking deployment status ==
{"@timestamp":"2020-07-06T06:17:03.231814 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"debug","message":"PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 1, in use: 1, waiting_in_queue: 0"}
{"@timestamp":"2020-07-06T06:17:03.911123 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"MIQ(Vmdb::Loggers.apply_config) Log level for azure.log has been changed to [WARN]"}
{"@timestamp":"2020-07-06T06:17:03.911782 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"MIQ(Vmdb::Loggers.apply_config) Log level for vim.log has been changed to [WARN]"}
{"@timestamp":"2020-07-06T06:17:04.268087 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"MIQ(SessionStore) Using session_store: ActionDispatch::Session::MemCacheStore"}
{"@timestamp":"2020-07-06T06:17:04.724336 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"debug","message":"Dalli::Server#connect 172.30.102.24:11211"}
{"@timestamp":"2020-07-06T06:17:05.241529 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"Initializing Environment for API"}
{"@timestamp":"2020-07-06T06:17:05.242109 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":""}
{"@timestamp":"2020-07-06T06:17:05.242351 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"Static Configuration"}
{"@timestamp":"2020-07-06T06:17:05.242598 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"  module                  : api"}
{"@timestamp":"2020-07-06T06:17:05.242886 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"  name                    : API"}
{"@timestamp":"2020-07-06T06:17:05.243152 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"  description             : REST API"}
{"@timestamp":"2020-07-06T06:17:05.243342 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":""}
{"@timestamp":"2020-07-06T06:17:05.243573 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"Dynamic Configuration"}
{"@timestamp":"2020-07-06T06:17:05.252747 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"  token_ttl               : 10.minutes"}
{"@timestamp":"2020-07-06T06:17:05.253346 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"  authentication_timeout  : 30.seconds"}
{"@timestamp":"2020-07-06T06:17:05.253580 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"  max_results_per_page    : 1000"}
{"@timestamp":"2020-07-06T06:17:05.253942 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"info","message":"MIQ(Vmdb::Initializer.init) - Program Name: bin/rake, PID: 17, ENV['EVMSERVER']: "}
{"@timestamp":"2020-07-06T06:17:05.254959 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"debug","message":"PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 1, in use: 0, waiting_in_queue: 0"}
{"@timestamp":"2020-07-06T06:17:11.801246 ","hostname":"orchestrator-fb675b57b-v9tc7","pid":17,"tid":"2ae67b88d95c","level":"debug","message":"PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 1, in use: 1, waiting_in_queue: 0"}
Deployment status is new_replica
New replica is not supported, exiting..

- ManageIQ version:
- Minikube/KIND/OCP/CRC version: OCP4.3
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

@miq-bot add-label bug

**Comment by carbonin** [comment] 2020-07-07 13:50
Closing as a duplicate of https://github.com/ManageIQ/manageiq-pods/issues/430

What this usually means is that the env is a bit slower than we expect. You should be able to re-deploy with a larger value for the [initial delay](https://github.com/ManageIQ/manageiq-pods/blob/2b8519e5ec7e5ebe0bebc628bb2b8e2cf82eb761/parameters#L67)

**Closed by carbonin** 2020-07-07 13:50 UTC
Labels: bug
