### ISSUE TITLE
ext-db uses wrong DATABASE_ connection param and creates unnecessary postgresql service

### ISSUE THREAD

**Issue by tbielawa** [ManageIQ/manageiq-pods#232] opened 2017-10-05 23:53 UTC
# Description

1. The [miq-template-ext-db.yaml](https://github.com/ManageIQ/manageiq-pods/blob/650a4ec62542a957994c72617af56302c83360f5/templates/miq-template-ext-db.yaml) template installs an unnecessary `svc`: [`postgresql`](https://github.com/ManageIQ/manageiq-pods/blob/650a4ec62542a957994c72617af56302c83360f5/templates/miq-template-ext-db.yaml#L305-L316). This manifests as `manageiq-0` pod never being able to initialize itself due to the health check preformed against the `postgresql` service before starting the `manageiq-0` pod. The service never provides a viable route for a health check to reach.
1. The [`database-url`](https://github.com/ManageIQ/manageiq-pods/blob/650a4ec62542a957994c72617af56302c83360f5/templates/miq-template-ext-db.yaml#L34) key in the manageiq-secret uses the wrong template parameter when constructing the database connection string. For the external database configuration the connection string should connect to the `DATABASE_IP`, not the `DATABASE_SERVICE_NAME`, should it not?

# Expected Results
When the pod launches from the external-database template the application will connect to the postgresql database given by the `DATABASE_IP` template parameter.

# Observed Results
Before the pod can launch there is what appears to be a service health check ran. It looks like this in the logs from the pod.

**(Relevant) Services Defined At This Time** 
```
[root@m01 ~]# oc get svc
NAME               CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
memcached          172.30.229.164   <none>        11211/TCP        2m
postgresql         172.30.248.193   <none>        5432/TCP         2m
```

Logs:

```
== Checking 172.30.229.164:11211 status ==
--
  | Ncat: No route to host.
  | Ncat: No route to host.
  | 172.30.229.164:11211 - accepting connections
  | == Checking 172.30.248.193:5432 status ==
  | Ncat: No route to host.
  | Ncat: No route to host.
  | Ncat: No route to host.
```

Health Checks:
1. `Checking 172.30.229.164:11211 status` is to the memcached service. This recovers and then we move on to the next service depencency.
1. `Checking 172.30.248.193:5432 status` is to the postgresql service. This does not recover. This message will go on and on...

If we delete the `postgresql` service and re-create the manageiq-0 pod then we see this in the logs

```
== Checking 172.30.229.164:11211 status ==
--
  | 172.30.229.164:11211 - accepting connections
  | Error something seems wrong, we need at least two parameters to check service status
```

This is again the memcached check, and it is healthy. However I am unsure what the last line about requiring two parameters is all about. This is followed by:

```
== Writing encryption key ==
  | == Restoring PV data symlinks ==
  | rake aborted!
  | PG::ConnectionBad: could not translate host name "postgresql" to address: Name or service not known
  | /var/www/miq/vmdb/lib/tasks/evm_application.rb:144:in `deployment_status'
  | /var/www/miq/vmdb/lib/tasks/evm.rake:82:in `block (2 levels) in <top (required)>'
  | Tasks: TOP => evm:deployment_status
  | (See full trace by running task with --trace)
  | {"@timestamp":"2017-10-05T23:28:31.938717 ","hostname":"manageiq-0","pid":28,"tid":"2af2fb341138","level":"info","message":"MIQ(Vmdb::Loggers.apply_config) Log level for evm.log has been changed to [INFO]"}
  | {"@timestamp":"2017-10-05T23:28:31.938942 ","hostname":"manageiq-0","pid":28,"tid":"2af2fb341138","level":"info","message":"MIQ(Vmdb::Loggers.apply_config) Log level for vim.log has been changed to [WARN]"}
...
```

The pod is still trying to connect to the service address, `postgresql`, because of how the [`database-url`](https://github.com/ManageIQ/manageiq-pods/blob/650a4ec62542a957994c72617af56302c83360f5/templates/miq-template-ext-db.yaml#L34) key is not correctly defined.

Then there is:
```
...
{"@timestamp":"2017-10-05T23:28:32.219198 ","hostname":"manageiq-0","pid":28,"tid":"2af2fb341138","level":"info","message":"MIQ(Vmdb::Initializer.init) - Program Name: bin/rake, PID: 28, ENV['MIQ_GUID']: , ENV['EVMSERVER']: "}
  | Could not find a suitable deployment type, exiting..
  | /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `initialize': could not translate host name "postgresql" to address: Name or service not known (PG::ConnectionBad)
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `new'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/pg-0.18.4/lib/pg.rb:45:in `connect'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
  | from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_handling.rb:91:in `connection'
  | from /var/www/miq/vmdb/app/models/miq_server/environment_management.rb:66:in `validate_database'
  | from /var/www/miq/vmdb/app/models/miq_server.rb:159:in `start'
  | from /var/www/miq/vmdb/lib/workers/evm_server.rb:27:in `start'
  | from /var/www/miq/vmdb/lib/workers/evm_server.rb:48:in `start'
  | from /var/www/miq/vmdb/lib/workers/bin/evm_server.rb:4:in `<main>'
...
```
 
I've been able to get a working install with an ext db if I start all over and edit the `manageiq-ext-db` template to use use `DATABASE_IP` instead of `DATABASE_SERVICE_NAME` and delete the [`postgresql` service](https://github.com/ManageIQ/manageiq-pods/blob/650a4ec62542a957994c72617af56302c83360f5/templates/miq-template-ext-db.yaml#L305-L316) from the template. 

---

While writing up this issue I did notice one new thing, there is a postgresql `Endpoints` object defined as well. This object makes reference of the `DATABASE_IP` and `_PORT`. Are the `service` and the `endpoint` supposed to be connected together somehow? If not then I'll submit a PR to fix the issue with the template in the way I described above.

**Comment by carbonin** [comment] 2017-10-06 12:38
I'll take a look at this today.

It seems to be related to https://github.com/ManageIQ/manageiq-pods/pull/223

Will update here when I have more info.

**Comment by carbonin** [comment] 2017-10-06 12:48
Also, the process for using an external service is documented [here](https://docs.openshift.org/latest/dev_guide/integrating_external_services.html#defining-a-service-for-an-external-database), this is the setup we were working from. Based on this documentation, I think we will stick with the service + endpoint solution (rather than using the IP directly).

**Comment by tbielawa** [comment] 2017-10-06 12:55
Ah ha! That PR explains a lot

```diff
+check_svc_status ${MEMCACHED_SERVICE_HOST} ${MEMCACHED_SERVICE_PORT}
+check_svc_status ${POSTGRESQL_SERVICE_HOST} ${POSTGRESQL_SERVICE_PORT}
```

That explains why we see the memcahed check followed by `Error something seems wrong, we need at least two parameters to check service status`.

**Comment by tbielawa** [comment] 2017-10-06 12:55
@carbonin  said
> Also, the process for using an external service is documented here, this is the setup we were working from. Based on this documentation, I think we will stick with the service + endpoint solution (rather than using the IP directly).`

Sounds good to me :thumbsup:

**Comment by fbladilo** [comment] 2017-10-06 13:35
@tbielawa We follow the official external service docs as @carbonin noted, in which, an internal service actually connects external endpoints with an external DATABASE_IP.

**Comment by carbonin** [comment] 2017-10-06 13:42
I can't seem to reproduce this.... Following the README I was able to set everything up fine.

I created the project with the following command:
`oc new-app --template=manageiq-ext-db -p DATABASE_IP=192.168.211.156 -p DATABASE_USER=root -p DATABASE_PASSWORD=smartvm -p DATABASE_NAME=vmdb_production`

Then the logs from the manageiq-0 pod seem fine ...
```
== Checking 172.30.214.103:11211 status ==
Ncat: Connection timed out.
172.30.214.103:11211 - accepting connections
== Checking 172.30.0.80:5432 status ==
172.30.0.80:5432 - accepting connections
```

Looks like the service (which points to the external endpoint) is getting a cluster IP and `$POSTGRESQL_SERVICE_HOST` is pointing to that ip.

This all seems expected.

**Comment by fbladilo** [comment] 2017-10-06 14:42
@tbielawa Can you reach the external database from any node of the OpenShift cluster on port 5432 (default)?

**Comment by tbielawa** [comment] 2017-10-06 14:43
@carbonin I'll get some debug info for you asap. I'm bringing up another postgres server now for testing further.

**Comment by carbonin** [comment] 2017-10-06 14:53
Some more detail from my working setup:

```bash
10:51:21:~/Source/manageiq-pods (master)$ oc get endpoints
NAME               ENDPOINTS              AGE
ansible            <none>                 21m
httpd              172.17.0.8:80          21m
httpd-auth-api     172.17.0.8:8080        21m
manageiq           172.17.0.6:80          21m
manageiq-backend   <none>                 21m
memcached          172.17.0.7:11211       21m
postgresql         192.168.211.156:5432   21m


10:51:27:~/Source/manageiq-pods (master)$ oc get service
NAME               CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
ansible            172.30.250.129   <none>        80/TCP,443/TCP   21m
httpd              172.30.151.89    <none>        80/TCP           21m
httpd-auth-api     172.30.152.18    <none>        8080/TCP         21m
manageiq           None             <none>        80/TCP           21m
manageiq-backend   None             <none>                         21m
memcached          172.30.209.133   <none>        11211/TCP        21m
postgresql         172.30.173.243   <none>        5432/TCP         21m


10:51:43:~/Source/manageiq-pods (master)$ oc describe endpoints postgresql
Name:		postgresql
Namespace:	manageiq
Labels:		app=manageiq-ext-db
		template=manageiq-ext-db
Annotations:	openshift.io/generated-by=OpenShiftNewApp
Subsets:
  Addresses:		192.168.211.156
  NotReadyAddresses:	<none>
  Ports:
    Name	Port	Protocol
    ----	----	--------
    postgresql	5432	TCP

Events:	<none>


10:51:48:~/Source/manageiq-pods (master)$ oc describe service postgresql
Name:			postgresql
Namespace:		manageiq
Labels:			app=manageiq-ext-db
			template=manageiq-ext-db
Annotations:		description=Remote database service
			openshift.io/generated-by=OpenShiftNewApp
Selector:		<none>
Type:			ClusterIP
IP:			172.30.173.243
Port:			postgresql	5432/TCP
Endpoints:		192.168.211.156:5432
Session Affinity:	None
Events:			<none>

```

**Comment by tbielawa** [comment] 2017-10-06 14:54
@carbonin thank you! That's exactly what I was going to followup and ask from you :grinning:

**Comment by carbonin** [comment] 2017-10-06 15:00
Feels like it might be the ClusterIP on the service.

If you don't have a cluster IP there the service wouldn't be routable, but the external IP would be ... just a guess

**Comment by tbielawa** [comment] 2017-10-06 15:28
I made a new project and created a postgresql pod from the included database templates

```
[root@m01 ~]# oc get services
NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
postgresql   172.30.135.110   <none>        5432/TCP   3m

[root@m01 ~]# oc describe service postgresql
Name:                   postgresql
Namespace:              pg
Labels:                 app=postgresql-persistent
                        template=postgresql-persistent-template
Annotations:            template.openshift.io/expose-uri=postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
Selector:               name=postgresql
Type:                   ClusterIP
IP:                     172.30.135.110
Port:                   postgresql      5432/TCP
Endpoints:              10.130.0.3:5432
Session Affinity:       None
Events:                 <none>
```

And the endpoints

```
[root@m01 ~]# oc get endpoints 
NAME         ENDPOINTS         AGE
postgresql   10.130.0.3:5432   4m

[root@m01 ~]# oc describe endpoints postgresql
Name:           postgresql
Namespace:      pg
Labels:         app=postgresql-persistent
                template=postgresql-persistent-template
Annotations:    <none>
Subsets:
  Addresses:            10.130.0.3
  NotReadyAddresses:    <none>
  Ports:
    Name        Port    Protocol
    ----        ----    --------
    postgresql  5432    TCP

Events: <none>
```

Database is up and running now

```
postgres=# CREATE DATABASE miq;
CREATE DATABASE
postgres=# ALTER DATABASE miq OWNER TO miq ;
ALTER DATABASE
postgres=# \list
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
-----------+----------+----------+------------+------------+-----------------------
 miq       | miq      | UTF8     | en_US.utf8 | en_US.utf8 | 
postgres=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 miq       | Superuser, Create role, Create DB                          | {}
```

From what I've gathered I must configure the template such that DATABASE_IP parameter has the postgresql service's ClusterIP, which in this case is `172.30.135.110`

I have constructed my ansible inventory as such:

```
[OSEv3:vars[
openshift_management_app_template=miq-template-ext-db
openshift_management_install_cfme=true
openshift_management_template_parameters={'APPLICATION_MEM_REQ': '3000Mi', 'ANSIBLE_MEM_REQ': '512Mi', 'DATABASE_USER': 'miq', 'DATABASE_PASSWORD': 'miq', 'DATABASE_IP': '172.30.135.110', 'DATABASE_PORT': '5432', 'DATABASE_NAME': 'miq' }
``` 

And I installed manageiq using this playbook:

```
ansible-playbook -vv -i hosts-local-cfme4.6 ./playbooks/byo/openshift-management/config.yml
```

Now I am here, looking at the manageiq-0 logs

```
[root@m01 ~]# oc logs -f manageiq-0 
== Checking 172.30.251.186:11211 status ==
Ncat: No route to host.
Ncat: No route to host.
172.30.251.186:11211 - accepting connections
== Checking 172.30.151.68:5432 status ==
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
Ncat: No route to host.
```

Let's look at the services

```
[root@m01 ~]# oc get services
NAME               CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
ansible            172.30.194.183   <none>        80/TCP,443/TCP   2m
httpd              172.30.168.23    <none>        80/TCP           2m
manageiq           None             <none>        80/TCP           2m
manageiq-backend   None             <none>                         2m
memcached          172.30.251.186   <none>        11211/TCP        2m
postgresql         172.30.151.68    <none>        5432/TCP         2m

[root@m01 ~]# oc describe service postgresql 
Name:                   postgresql
Namespace:              openshift-management
Labels:                 template=manageiq-ext-db
Annotations:            description=Remote database service
Selector:               <none>
Type:                   ClusterIP
IP:                     172.30.151.68
Port:                   postgresql      5432/TCP
Endpoints:              172.30.135.110:5432
Session Affinity:       None
Events:                 <none>
```

And we have these endpoints:

```
[root@m01 ~]# oc get endpoints
NAME               ENDPOINTS             AGE
ansible            <none>                4m
httpd              10.129.0.12:80        3m
manageiq                                 4m
manageiq-backend   <none>                4m
memcached          10.128.0.9:11211      4m
postgresql         172.30.135.110:5432   4m

[root@m01 ~]# oc get endpoints postgresql
NAME         ENDPOINTS             AGE
postgresql   172.30.135.110:5432   4m
```

So the manageiq-0 log is trying to connect to `172.30.151.68` which is the postgresql service Cluster IP. `svc/postgresql` notes an `IP` of `172.30.135.110` in the `Endpoints` parameter. The postgresql endpoint also lists this ip.

Now, if I install `nmap` after `rsh`ing into the manageiq-0 pod I can test the following connections


**Port 5432 on the postgresl service IP for the manageiq project**
```
sh-4.2# nmap -p 5432 172.30.151.68

Starting Nmap 6.40 ( http://nmap.org ) at 2017-10-06 15:26 UTC
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.07 seconds
```

OK. That was filtered, let's try with `-Pn`:

```
sh-4.2# nmap -Pn -p 5432 172.30.151.68

Starting Nmap 6.40 ( http://nmap.org ) at 2017-10-06 15:26 UTC
Nmap scan report for postgresql.openshift-management.svc.cluster.local (172.30.151.68)
Host is up.
PORT     STATE    SERVICE
5432/tcp filtered postgresql

Nmap done: 1 IP address (1 host up) scanned in 2.05 seconds
```

Still filtered connecting to the local postgresql service. Now let's try to connect to the IP of the postgresql pod I'm running in another project

```
sh-4.2# nmap -p 5432 172.30.135.110

Starting Nmap 6.40 ( http://nmap.org ) at 2017-10-06 15:27 UTC
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.07 seconds
```

Filtered. OK, add `-Pn` again:

```
sh-4.2# nmap -Pn -p 5432 172.30.135.110

Starting Nmap 6.40 ( http://nmap.org ) at 2017-10-06 15:27 UTC
Nmap scan report for postgresql.pg.svc.cluster.local (172.30.135.110)
Host is up (0.000087s latency).
PORT     STATE SERVICE
5432/tcp open  postgresql

Nmap done: 1 IP address (1 host up) scanned in 0.06 seconds
```

I'm not sure what all of this really means as far as rooting out the source of the problem.

**Comment by tbielawa** [comment] 2017-10-06 17:51
While speaking with @fbladilo we may have narrowed down the source of this failure. As I am running my PostgreSQL server in a pod in a different project on the same OCP cluster, it is possible that manageiq-0 could literally not reach the network that the postgres service was exposed on in the other project.

I attempted installing my cluster using `os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'` and then [joining the namespace networks together](https://docs.openshift.com/container-platform/3.5/admin_guide/managing_networking.html#joining-project-networks), however, the results were the same.

My testing is failing because of network conditions. I couldn't get a test instance up in our AWS (no permissions) so I'll try getting one running on one of my masters/nodes and see how that works out.

**Comment by carbonin** [comment] 2017-10-06 17:54
> From what I've gathered I must configure the template such that DATABASE_IP parameter has the postgresql service's ClusterIP, which in this case is 172.30.135.110

That assumption might be the issue. I set the DATABASE_IP to the *external* address of the server in my case, a VM.

I'm not sure what would change if you were trying to use a separate openshift project to host the PG server, but this is not the intended usecase for the external database template. The reason it exists is so that the customers who need high levels of database performance can run the DB on dedicated servers, or bare metal if necessary. I would suggest testing with a similar setup.

**Comment by tbielawa** [comment] 2017-10-06 18:54
* Set up postgresql on another vm (one of my masters, to be explicit)
* Enable firewall/iptables holes
* Create miq role with `createuser` command and ensure they can create databases
* Create database `miq`, make `miq` role the owner

ManageIQ connected just swell this time. It even began migrating the database. I was about to celebrate with some champaign until the db migration failed on me :-\

```
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec': PG::UndefinedTable: ERROR:  relation "chargeable_fields" does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT "chargeable_fields".* FROM "chargeable_fields"
                                          ^
: SELECT "chargeable_fields".* FROM "chargeable_fields"
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:377:in `select_prepared'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:39:in `select_all'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/querying.rb:39:in `find_by_sql'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation.rb:706:in `exec_queries'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation.rb:583:in `load'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation.rb:260:in `records'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/relation/delegation.rb:38:in `map'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.6/lib/active_support/core_ext/enumerable.rb:59:in `index_by'
        from /var/www/miq/vmdb/app/models/chargeable_field.rb:69:in `seed'
        from /var/www/miq/vmdb/lib/evm_database.rb:80:in `block (2 levels) in seed'
        from /var/www/miq/vmdb/lib/evm_database.rb:69:in `each'
        from /var/www/miq/vmdb/lib/evm_database.rb:69:in `block in seed'
        from /var/www/miq/vmdb/lib/extensions/ar_table_lock.rb:21:in `block (2 levels) in with_lock'
        from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
        from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
        from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
        from /var/www/miq/vmdb/lib/extensions/ar_table_lock.rb:21:in `block in with_lock'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.6/lib/active_record/transactions.rb:211:in `transaction'
        from /var/www/miq/vmdb/lib/extensions/ar_table_lock.rb:15:in `with_lock'
        from /var/www/miq/vmdb/lib/evm_database.rb:68:in `seed'
        from /var/www/miq/vmdb/lib/evm_database.rb:56:in `seed_last'
        from /var/www/miq/vmdb/app/models/miq_server.rb:227:in `start'
        from /var/www/miq/vmdb/lib/workers/evm_server.rb:27:in `start'
        from /var/www/miq/vmdb/lib/workers/evm_server.rb:48:in `start'
        from /var/www/miq/vmdb/lib/workers/bin/evm_server.rb:4:in `<main>'
[root@m01 ~]# systemctl status postgresql.service
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-10-06 18:39:58 UTC; 13min ago
```

**Comment by carbonin** [comment] 2017-10-20 18:30
Can we close this as the issue ended up being a combination of environment issues (using a database within a separate project and also using the wrong PG version)?

**Comment by carbonin** [comment] 2017-12-15 20:55
Closing this as the issues were environmental.

**Closed by carbonin** 2017-12-15 20:55 UTC
Labels: bug
