### ISSUE TITLE
ManageIQ template DATABASE_NAME variable doesn't make it to manageiq pod configuration

### ISSUE THREAD

**Issue by joelddiaz** [ManageIQ/manageiq-pods#184] opened 2017-07-14 18:33 UTC
When trying to use the mangeiq template to point to an external Postgres DB, the manageiq pod was set up in a way where it was attempting to connect to the external Postgres DB with the DB name 'vmdb_production'. The value of DATABASE_NAME passed to the template was not 'vmdb_production'.

After I manually created a DB with the name 'vmdb_production', the manageiq pod was able to come up successfully.

**Comment by carbonin** [comment] 2017-07-14 18:43
Can you provide the steps you took to deploy the application? Especially any error messages in the manageiq logs (`/var/www/miq/vmdb/log/evm.log`) on the frontend pod or the standard out of that pod.

Additionally can you provide the value of the `DATABASE_URL` environment variable from the manageiq-frontend pod?

**Comment by joelddiaz** [comment] 2017-07-14 18:58
After importing the template, ran:

oc new-app --template=manageiq-ext-db -p DATABASE_IP=172.31.54.216 -p DATABASE_USER=pg_admin -p DATABASE_PASSWORD=$PG_PASSWORD -p DATABASE_NAME=cmops_pgtest -p MEMCACHED_IMG_TAG=memcached-latest-fine -p APPLICATION_IMG_TAG=app-latest-fine

You can see the DATABASE_NAME was set to 'cmops_pgtest'. I had to externally create the 'vmdb_production' DB for the manageiq pod to successfully start up:

createdb -h 172.31.54.216 -U pg_admin vmdb_production

I don't have the exact log output from the manageiq pod, but there were some output somewhere that indicated that the workaround was to manually create the 'vmdb_production' DB. Perhaps @simon3z can explain better what we saw while trying to bring up the manageiq pod.

**Comment by bazulay** [comment] 2017-07-16 17:48
@carbonin @joelddiaz 
Nick Joel is working on the fine branch , but I assume that master has the same issue.
When I tested external db , I encountered the same phenomena.

**Comment by simon3z** [comment] 2017-07-17 09:10
@joelddiaz @carbonin @bazulay please take a look at #183 which once merged (and images rebuilt) should handle this.

**Comment by hahnn** [comment] 2017-07-24 14:37
What port are you using? Because if you use a port different than 5432, which is the default postgreSQL port, it will not work.
That's what I've explained in the issue #177 opened 20 days ago. I'm convinced there's a bug here. Maybe that'll be confirmed (or not) when an answer will be provided, or maybe this issue is solved I've to check.

**Comment by joelddiaz** [comment] 2017-07-24 14:56
Using the standard PostgreSQL port (5432).

**Comment by fbladilo** [comment] 2017-07-25 14:09
@hahnn @joelddiaz Remote port issue addressed via #186 , other issues as @simon3z  pointed on #183 and related.

**Comment by carbonin** [comment] 2017-08-25 17:37
Both of the PRs @fbladilo mentioned are merged. Has this issue been addressed?

**Comment by fbladilo** [comment] 2017-09-13 21:18
@joelddiaz @hahnn Are we good to resolve this issue? Thanks.

**Comment by carbonin** [comment] 2017-09-14 13:22
This has been waiting on feedback for multiple weeks, so I'm going to go ahead and close it.

**Closed by carbonin** 2017-09-14 13:22 UTC
