### ISSUE TITLE
Add imagePullSecret to operator 

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#473] opened 2020-04-29 14:13 UTC
@miq-bot add_label enhancement

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We need to add the field of `imagePullSecret` to each images for the manageIQ operator to make sure it can still pull images even if the registry is not public.

FYI @Fryguy @carbonin 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by carbonin** [comment] 2020-04-29 14:15
Duplicate of https://github.com/ManageIQ/manageiq-pods/issues/472

**Closed by carbonin** 2020-04-29 14:15 UTC
